language: python
python:
  - 2.7
  - 3.5

before_install:
  - sudo apt-get update -q
  - sudo apt-get install libxtst-dev python-opencv -y
  - sudo cp /usr/lib/pyshared/python2.7/cv2.so /home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages/
  - sudo ln /dev/null /dev/raw1394
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
install:
  - pip install .
  - pip install pytest-cov

script: cd test ; pytest --cov=sikuli unit/
