language: python
python:
  - 2.7
  - 3.5

before_install:
  - sudo apt-get update -q
  - sudo apt-get install libxtst-dev -y
install: pip install .

# just check that we are installed
# test1231
script: true
