language: python
sudo: false
python:
- 3.6

addons:
  apt:
    packages:
    - libxtst-dev
    - python-opencv

before_install:
- |
  export DISPLAY=:99.0
  sh -e /etc/init.d/xvfb start
- |
  if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
  curl --silent http://code.shishnet.org/files/opencv.tar.gz | tar xzv -C ~/
  cp ~/opencv/cv2.cpython-36m-x86_64-linux-gnu.so $VIRTUAL_ENV/lib/python3.6/site-packages/
  fi

install: pip install pytest-cov .

script: cd test ; LD_LIBRARY_PATH=/home/travis/opencv/ py.test --cov=sikuli unit/
