language: python
python:
  - 2.7
  - 3.5

before_install:
  - sudo apt-get update -q
  - sudo apt-get install libxtst-dev -y
install:
  - pip install .
  - pip install pytest-cov

script: pytest --cov=sikuli test/unit/
