language: python
sudo: false
python:
- 2.7
- 3.5

addons:
  apt:
    packages:
    - libxtst-dev
    - python-opencv

before_install:
- |
  export DISPLAY=:99.0
  sh -e /etc/init.d/xvfb start
- |
  if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
  cp /usr/lib/pyshared/python2.7/cv2.so $VIRTUAL_ENV/lib/python2.7/site-packages/
  fi
- |
  if [[ $TRAVIS_PYTHON_VERSION == 3.5 ]]; then
  curl http://code.shishnet.org/files/opencv.tar.xz | tar xv --xz
  cp ~/opencv/cv2.cpython-35m-x86_64-linux-gnu.so $VIRTUAL_ENV/lib/python3.5/site-packages/
  fi

install: pip install pytest-cov .

script: cd test ; LD_LIBRARY_PATH=/home/travis/opencv/ py.test --cov=sikuli unit/
