language: python
sudo: required
dist: xenial
python:
- 3.6

addons:
  apt:
    packages:
    - libxtst-dev
    - python-opencv

before_install:
- |
  export DISPLAY=:99.0
  sh -e /etc/init.d/xvfb start
- |
  if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
  wget http://code.shishnet.org/files/opencv-3.4.1-py3.6.3.tar.xz
  tar xf opencv*.tar.xz -C ~/
  cp ~/opencv/cv2.*.so $VIRTUAL_ENV/lib/python${TRAVIS_PYTHON_VERSION}/site-packages/
  fi

install: pip install pytest-cov .

script: cd test ; LD_LIBRARY_PATH=/home/travis/opencv/ py.test --cov=sikuli unit/
